config/routes.rb
Rails.application.routes.draw do
  resources :new_skills
  resources :new_drops
  resources :drops
  resources :enemy_data
  resources :enemies
  resources :parties
  resources :aps
  resources :garden_names
  get "skill/history",  :to => "skills#history",  :as => "skill_history"
  resources :skills
  resources :skill_data
  resources :type_names
  get "status/graphs",  :to => "statuses#graphs",  :as => "status_graphs"
  resources :statuses
  resources :uploaded_checks
  resources :proper_names
  resources :names
  get 'top_page/privacy'
  root 'top_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def index
    @latest_created = Status.maximum("created_at")
    @uploaded_created = UploadedCheck.maximum("created_at")
  end
end

app/helpers/top_page_helper.rb
module TopPageHelper
    def top_date_text(created_at, uploaded)
        if !created_at then return "---" end
        
        text = created_at.to_s(:jp_date)

        if created_at == uploaded then
            text += " 早朝のデータまで反映しています"
        else
            text += " のデータに更新中です…"
        end

        text
    end
end

app/views/top_page/index.html.haml
%h1 ソラニワデータ小屋
%p
  このサイトでは『
  %a{:href => "http://st.x0.to/", :target => "_blank"} Stroll Green -restroll-
  』を解析して得られる情報を扱ってました。
  %br
  ゲーム終了に伴い、全戦闘結果から取得したデータを残しています。
%br
%p= top_date_text(@latest_created, @uploaded_created)

.card.top
  .card-body
    %h2 サイトマップ
    .row
      .col-md-6
        %ul
          %li 個人データ
          %ul
            %li= link_to "キャラクター一覧", names_path
            %br
            %li= link_to "ステータス一覧", statuses_path
            %li= link_to "設定スキル一覧", skills_path
      .col-md-6
        %ul
          %li 結果データ
          %ul
            %li= link_to "結果一覧", aps_path
            %li= link_to "獲得アイテム一覧", drops_path
    .row
      .col-md-6
        %ul
          %li グラフデータ
          %ul
            %li= link_to "ステータスグラフ", status_graphs_path + "?graph=on"
            %li= link_to "設定スキル遷移グラフ", skill_history_path + "?graph=on"
      .col-md-6
        %ul
          %li 新出データ
          %ul
            %li= link_to "新出設定スキル一覧", new_skills_path
            %li= link_to "新出獲得アイテム一覧", new_drops_path

.card.top
  .card-body
    %h2 更新履歴
    %div
      %ul
        %li 2021/6/24
        %ul
          %li
            Stroll Green -restroll-の結果データに差し替え
    %p
      %span.example_select.example_toggle.pointer
        = fa_icon "history"
        古い履歴
        - act_desc(false)
    .closed
      %ul
        %li 2020/6/16
        %ul
          %li
            ゲーム終了・本家結果削除に伴い結果へのリンクを削除
          %li
            = link_to "キャラクター一覧", names_path
            を公開
        %li 2020/5/22
        %ul
          %li
            Stroll Green -Green Festival-の結果データに差し替え
        %li 2019/9/15
        %ul
          %li
            = link_to "ステータスグラフ", status_graphs_path + "?graph=on"
            を公開
          %li
            = link_to "設定スキル遷移グラフ", skill_history_path + "?graph=on"
            を公開
        %li 2019/8/22
        %ul
          %li
            = link_to "獲得アイテム一覧", drops_path
            、
            = link_to "新出設定スキル一覧", new_skills_path
            、
            = link_to "新出獲得アイテム一覧", new_drops_path
            を公開
        %li 2019/8/13
        %ul
          %li
            = link_to "設定スキル一覧", skills_path
            に性質、発動数、消費コストを表示、検索ができるように
        %li 2019/8/1
        %ul
          %li
            = link_to "結果一覧", aps_path
            を公開
        %li 2019/7/30
        %ul
          %li
            = link_to "設定スキル一覧", skills_path
            にステータス、メインタイプでの絞り込み機能を追加
        %li 2019/7/28
        %ul
          %li サイト公開

app/views/top_page/privacy.html.haml
%h1 プライバシーポリシー
%p 本文書は、当サイト（データ小屋）における個人情報の保護およびその適切な取り扱いについての方針を示したものです。
%br
%h2 当サイトが利用しているアクセス解析ツールに関して
%p (Googleアナリティクス等を使用している場合に記述)
%br
%p 最終更新日：20--年-月-日
%br